
[env]
TERM = "xterm-256color"


[font]	
size = 13
normal = {family = "FiraCode Nerd Font Mono"}

[window]
padding = { x = 8, y = 8 }
opacity = 1
decorations = "Buttonless"

[general]
import = [
	"~/.config/alacritty/monocode-panther.toml"
]
